# Generated by Django 5.1.6 on 2025-05-28 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channelmembers',
            old_name='channelId',
            new_name='channel',
        ),
        migrations.RenameField(
            model_name='channelmembers',
            old_name='userId',
            new_name='user',
        ),
    ]
