# Generated by Django 5.1.6 on 2025-04-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='nickname',
            field=models.CharField(default='', max_length=30),
        ),
    ]
