# Generated by Django 5.1.6 on 2025-04-21 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_messages_options_messages_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='userId',
            new_name='author',
        ),
    ]
